package com.cewar.util.json;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

import com.cewar.util.NameFormatter;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.core.util.DefaultIndenter;
import com.fasterxml.jackson.core.util.DefaultPrettyPrinter;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

/**
 * Takes a .json file generated by 
 * LINK https://csvjson.com/csv2json after downloading google sheet as .csv
 * and converts it into the proper formatting
 */
public class JsonFixer {

    private final static String INDEX_SOURCE = "ce-war\\src\\main\\java\\com\\cewar\\util\\json\\cardIndexToFix.json";
    private final static String INDEX_DEST = "ce-war\\src\\main\\resources\\private\\cardIndex.json";

    public static void main(String[] args) throws IOException {

        // Scan source file for preprocessing
        Scanner scanner = new Scanner(new File(INDEX_SOURCE));
        scanner.useDelimiter("\\Z");
        String dataSource = scanner.next();
        scanner.close();

        // Preprocess scanned file
        dataSource = fixSmartChars(dataSource);

        // Read Json from file
        ObjectMapper objectMapper = new ObjectMapper();

        // Configure pretty printer to use 4 spaces for indentation, rather than the default 2
        objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
        DefaultPrettyPrinter.Indenter indenter = new DefaultIndenter("    ", DefaultIndenter.SYS_LF);
        DefaultPrettyPrinter printer = new DefaultPrettyPrinter();
        printer.indentObjectsWith(indenter);
        printer.indentArraysWith(indenter);

        List<Map<String, String>> toFix = objectMapper.readValue(dataSource, new TypeReference<List<Map<String, String>>>(){});
        List<Map<String, Object>> fixedCards = new ArrayList<>();

        for (int i = 0; i < toFix.size(); i++) {
            Map<String, Object> newObj = new HashMap<>();
            Map<String, String> oldObj = toFix.get(i);

            // Name
            newObj.put("name", oldObj.get("Card Name"));

            // Rarity
            String rarityString = oldObj.get("Rarity").toUpperCase();
            switch (rarityString) {
                case ("ULTRA RARE"):
                    newObj.put("rarity", "ULTRA_RARE");
                    break;
                default:
                    newObj.put("rarity", rarityString);
            }

            // Type
            newObj.put("type", oldObj.get("Card Type").toUpperCase());

            // Attributes
            String atrString = oldObj.get("Card Attribute").toUpperCase();
            if (atrString.length() == 0) {
                newObj.put("attribute", new int[0]);
            } else {
                newObj.put("attribute", atrString.split(", "));
            }
            
            // Archetypes
            String archString = oldObj.get("Archetypes").toUpperCase();
            if (archString.length() == 0) {
                newObj.put("archetype", new int[0]);
            } else {
                newObj.put("archetype", archString.split(", "));
            }

            // Attack
            // Do not display: use -1
            // "???": use -2
            String atkString = oldObj.get("ATK");
            if (atkString.equals("???")) {
                newObj.put("attack", -2);
            } else {
                atkString = atkString.replaceAll("[^0-9]", ""); // Replace any odd characters
                if (atkString.length() == 0) {
                    newObj.put("attack", -1);
                } else {
                    newObj.put("attack", Integer.parseInt(atkString));
                }
            }

            // Size
            String sizeString = oldObj.get("Size");
            if (sizeString.length() == 0) {
                newObj.put("size", new int[0]);
            } else {
                String[] sizeArr = sizeString.split("x");
                if (sizeArr.length == 2) {
                    newObj.put("size", new int[]{Integer.parseInt(sizeArr[0]), Integer.parseInt(sizeArr[1])});
                } else {
                    throw new IllegalArgumentException("Invalid size for: " + Arrays.toString(sizeArr));
                }
            }

            // Is God? (tested before Health)
            String godHPString = oldObj.get("God HP");
            newObj.put("is_god", !(godHPString.length() == 0));

            // Health
            // Do not display: use -1
            // "???": use -2
            String healthString = oldObj.get("HP");
            if (godHPString.length() == 0 ^ healthString.length() == 0) {
                if (healthString.length() == 0) {
                    // Only God HP is defined
                    if (godHPString.equals("???")) {
                        newObj.put("health", -2);
                    } else {
                        newObj.put("health", Integer.parseInt(godHPString));
                    }
                } else {
                    // Only normal HP is defined
                    if (healthString.equals("???")) {
                        newObj.put("health", -2);
                    } else {
                        newObj.put("health", Integer.parseInt(healthString));
                    }
                }
            } else {
                if (godHPString.length() == 0) {
                    // Both God HP and normal HP are not defined
                    newObj.put("health", -1);
                } else {
                    throw new IllegalArgumentException("God HP and normal HP are both defined");
                }
            }

            // Materials
            // TODO I'm not doing this right now lol
            newObj.put("material", oldObj.get("Materials"));

            // Effect
            newObj.put("effect", oldObj.get("Effect").toString());

            // Flavor Text
            newObj.put("flavor_text", oldObj.get("Flavor Text"));

            // Create formatted name, for better user interface
            // File destination is stored as a string, relative to the "static" folder in the web application
            String formattedName = NameFormatter.formatName(oldObj.get("Card Name"));
            newObj.put("id", formattedName);

            // Art Source
            newObj.put("art", "images/cards/art/" + formattedName + ".png");
            newObj.put("full", "images/cards/full/" + formattedName + ".png");

            // Set User Card ID to default (-1)
            newObj.put("user_card_id", -1);

            // Put this formatted card in the fixed card List
            fixedCards.add(newObj);
        }

        objectMapper.writer(printer).writeValue(new File(INDEX_DEST), fixedCards);

    }

    /**
     * Fixes the annoying characters google sheets adds in
     * 
     * @param string
     * @return a formatted copy of this String
     */
    public static String fixSmartChars(String string) {
        return string
            .replaceAll("\u2026", "...")
            .replaceAll("\u2019", "'")
            .replaceAll("\u201c", "\\\\\"")
            .replaceAll("\u201d", "\\\\\"");
                // Explanation
                // 1. Written in code here as \\-\\-\" (hyphens used for readability)
                // 2. Tells code to replace smart quote in String with \\"
                // 3. JSON will read that as \"
                // 4. User will see "
    }
}
